In [1]:
[i for i in range(100)]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [3]:
import math
[math.sin(i) for i in range(361)]

[0.0,
 0.8414709848078965,
 0.9092974268256817,
 0.1411200080598672,
 -0.7568024953079282,
 -0.9589242746631385,
 -0.27941549819892586,
 0.6569865987187891,
 0.9893582466233818,
 0.4121184852417566,
 -0.5440211108893698,
 -0.9999902065507035,
 -0.5365729180004349,
 0.4201670368266409,
 0.9906073556948704,
 0.6502878401571168,
 -0.2879033166650653,
 -0.9613974918795568,
 -0.7509872467716762,
 0.14987720966295234,
 0.9129452507276277,
 0.8366556385360561,
 -0.008851309290403876,
 -0.8462204041751706,
 -0.9055783620066238,
 -0.13235175009777303,
 0.7625584504796027,
 0.956375928404503,
 0.27090578830786904,
 -0.6636338842129675,
 -0.9880316240928618,
 -0.404037645323065,
 0.5514266812416906,
 0.9999118601072672,
 0.5290826861200238,
 -0.428182669496151,
 -0.9917788534431158,
 -0.6435381333569995,
 0.2963685787093853,
 0.9637953862840878,
 0.7451131604793488,
 -0.158622668804709,
 -0.9165215479156338,
 -0.8317747426285983,
 0.017701925105413577,
 0.8509035245341184,
 0.9017883476488092,
 0

In [4]:
#list comprehension
[(i,j) for i in range(10) for j in range(i+1,10) if not i%2]

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (6, 7),
 (6, 8),
 (6, 9),
 (8, 9)]

In [5]:
# Generator ipv list. Verschil is () ipv [].
g = ((i,j) for i in range(10) for j in range(i+1,10) if not i%2)

In [6]:
g

<generator object <genexpr> at 0x0000000004991FC0>

In [7]:
for i,j in g:
    print(i,j)
#Na het uitvoeren van deze statements is g leeg.
#Wil je het nogmaals gebruiken moet de generator nogmaals maken
#Voordeel van een generator is dat er weinig geheugenbeslag plaats vind in tegenstelling tot lists 


0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
2 3
2 4
2 5
2 6
2 7
2 8
2 9
4 5
4 6
4 7
4 8
4 9
6 7
6 8
6 9
8 9


In [11]:
for i in (j for j in range(100) if not j%2):
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [16]:
#zip voegt dingen samen, bijvoorbeeld twee lijsten
#is ook een generator
alfabet='abcdefghijklmnopqrstuvwxyz'
nummers=range(1,27)
zipped=zip(alfabet,nummers)

In [19]:
for i in zipped:
    print(i)

('a', 1)
('b', 2)
('c', 3)
('d', 4)
('e', 5)
('f', 6)
('g', 7)
('h', 8)
('i', 9)
('j', 10)
('k', 11)
('l', 12)
('m', 13)
('n', 14)
('o', 15)
('p', 16)
('q', 17)
('r', 18)
('s', 19)
('t', 20)
('u', 21)
('v', 22)
('w', 23)
('x', 24)
('y', 25)
('z', 26)


In [20]:
#Na bovenstaande is zipped leeg, nogmaals uitvoeren geeft dan geen output
for i in zipped:
    print(i)

In [1]:
import numpy as np

In [2]:
r = np.arange(16).reshape(4,4)

In [3]:
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
r.reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [6]:
m=r.mean(axis=0)

In [7]:
m

array([ 6.,  7.,  8.,  9.])

In [8]:
r-m

array([[-6., -6., -6., -6.],
       [-2., -2., -2., -2.],
       [ 2.,  2.,  2.,  2.],
       [ 6.,  6.,  6.,  6.]])

In [9]:
r-m[:,None]

array([[-6., -5., -4., -3.],
       [-3., -2., -1.,  0.],
       [ 0.,  1.,  2.,  3.],
       [ 3.,  4.,  5.,  6.]])

In [10]:
r.T-m

array([[-6., -3.,  0.,  3.],
       [-5., -2.,  1.,  4.],
       [-4., -1.,  2.,  5.],
       [-3.,  0.,  3.,  6.]])

In [11]:
(r.T-m).T

array([[-6., -5., -4., -3.],
       [-3., -2., -1.,  0.],
       [ 0.,  1.,  2.,  3.],
       [ 3.,  4.,  5.,  6.]])

In [12]:
r-m.T

array([[-6., -6., -6., -6.],
       [-2., -2., -2., -2.],
       [ 2.,  2.,  2.,  2.],
       [ 6.,  6.,  6.,  6.]])

In [13]:
r.reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])